#FirstJoin
first_join_message_enabled: true
first_join_message: "Welcome in the best server EU"
#NormalJoin
join_message_enabled: true
join_message: "Welcome back in the best server EU"

#Towns Config:
next_id: 1
create_gold_price: 50
claim_chunk_price: 5
new_town_created_message: " has founded a new Town!"
chunk_already_claim: "This chunk is already claim by someone!"
only_mayor_message: "Only mayor/comayor can do this action!"
not_part_town: "You are not part of a town!"
part_town: "He is part of a town!"
not_invited: "You are not invited by no one! (sad)"
claim_not_adjacent: "This chunk is not adjacent!"
cant_place_block: "Can't build here!"
cant_kill_animals: "Can't kill here!"
cant_interact_here: "Can't Interact Here!"
cant_kill_monster: "Can't kill monster here!"
cant_kill_player: "Can't attacck here!"
player_not_online: "This player is offline!"
player_join_town: "You join the town: "