name: CityScape
version: '0.2.4'
main: pkg.cityScape.CityScape
api-version: '1.21'
authors: [ Nadoo ]
softdepend: ["PlaceholderAPI", "dynmap"]
commands:
  city:
    description: Comando principale per la città
    aliases: [c]
